/**
 * Type definitions mirroring the SQLite schema produced by scripts/02-04.
 * See data/bundle/kanji.sqlite generated by the Python pipeline.
 */

export type JlptNewLevel = 1 | 2 | 3 | 4 | 5;

/** Raw row shape returned by SQLite — JSON columns are still strings here. */
export interface KanjiRow {
  character: string;
  stroke_count: number;
  jlpt_old: number | null;
  jouyou_grade: number | null;
  frequency_rank: number | null;
  meanings_en: string;
  onyomi: string;
  kunyomi: string;
  radical_classical: number | null;
  jlpt_new: number | null;
}

/** Decoded kanji with JSON arrays parsed into native lists. */
export interface Kanji {
  character: string;
  strokeCount: number;
  jlptOld: number | null;
  jouyouGrade: number | null;
  frequencyRank: number | null;
  meaningsEn: string[];
  onyomi: string[];
  kunyomi: string[];
  radicalClassical: number | null;
  jlptNew: JlptNewLevel | null;
}

export interface RadicalDecomposition {
  radicalChar: string;
  count: number;
}

export function decodeKanji(row: KanjiRow): Kanji {
  return {
    character: row.character,
    strokeCount: row.stroke_count,
    jlptOld: row.jlpt_old,
    jouyouGrade: row.jouyou_grade,
    frequencyRank: row.frequency_rank,
    meaningsEn: JSON.parse(row.meanings_en) as string[],
    onyomi: JSON.parse(row.onyomi) as string[],
    kunyomi: JSON.parse(row.kunyomi) as string[],
    radicalClassical: row.radical_classical,
    jlptNew: row.jlpt_new as JlptNewLevel | null,
  };
}
