package io.github.tsuguchi.kanjibuilder.data

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase

/**
 * Room wrapper around the **bundled** static reference database. The actual
 * SQLite is generated by the Python pipeline (data/bundle/kanji.sqlite),
 * copied into app/src/main/assets/kanji.sqlite by a Gradle preBuild task,
 * and Room copies it from assets into the app's data dir on first launch.
 *
 * Treat this database as read-only: schema migrations are not needed because
 * we bump the `version` and re-ship a fresh asset.
 *
 * User progress (SRS, stages cleared) belongs in a separate Room database
 * that will be added later.
 */
@Database(
    entities = [Kanji::class, Radical::class, KanjiRadical::class],
    version = 1,
    exportSchema = true,
)
abstract class KanjiDatabase : RoomDatabase() {

    abstract fun kanjiDao(): KanjiDao

    companion object {
        @Volatile private var instance: KanjiDatabase? = null

        fun get(context: Context): KanjiDatabase =
            instance ?: synchronized(this) {
                instance ?: build(context).also { instance = it }
            }

        private fun build(context: Context): KanjiDatabase =
            Room.databaseBuilder(
                context.applicationContext,
                KanjiDatabase::class.java,
                "kanji.db",
            )
                .createFromAsset("kanji.sqlite")
                .fallbackToDestructiveMigration()
                .build()
    }
}
